### ISSUE TITLE
Arduino Language Server

### ISSUE THREAD

**Issue by thetic** [williamboman/nvim-lsp-installer#292]
**Which server would you like to request to be added?**
Server name: arduino_language_server
Server homepage (e.g., GitHub page): https://github.com/arduino/arduino-language-server

**Which languages does this server target?**
Languages: arduino

I have a rudimentary implementation here that probably doesn't work outside of Linux and misses some edge cases:

```lua
local arduino_config = function()
    local server_name = 'arduino_language_server'

    local server = require('nvim-lsp-installer.server')
    local root_dir = server.get_server_root_path(server_name)
    local go = require('nvim-lsp-installer.installers.go')
    local installers = require('nvim-lsp-installer.installers')
    local shell = require('nvim-lsp-installer.installers.shell')

    return server.Server:new({
        name = server_name,
        root_dir = root_dir,
        homepage = 'https://github.com/arduino/arduino-language-server',
        installer = installers.pipe({
            go.packages({
                'github.com/arduino/arduino-language-server',
            }),
            shell.bash(
                go.executable(root_dir, 'arduino-language-server')
                    .. 'config init --overwrite'
            ),
        }),
        default_options = {
            cmd = {
                go.executable(root_dir, 'arduino-language-server'),
                '-cli-config',
                '~/.arduino15/arduino-cli.yaml',
            },
        },
    })
end

require('nvim-lsp-installer.servers').register(arduino_config())
```

**Comment by williamboman** [comment]
Hello! I've actually been looking into this and have a branch ready for it. What's blocking it currently is that the cmd to start the server seems to rely on user-specific configs, such as the `-cli-config` option. Few questions:

- What is the `-cli-config` option? Is there some common path that this could default to, or is it generally always custom to each user? Is it a project-specific file, or a system-wide?
- Do you know if the `-cli` and `-clangd` options are needed? If yes, we could make sure to install `arduino-cli` and `clangd` as well.

**Comment by thetic** [comment]
>     * What does the `arduino-language-server config init --overwrite` command do?

In my case, I just wanted to ensure that a config existed. The server won't run without one.

>     * What is the `-cli-config` option? Is there some common path that this could default to, or is it generally always custom to each user? Is it a project-specific file, or a system-wide?

This is the default location. It appears to be a global config:

```yaml
board_manager:
  additional_urls: []
daemon:
  port: "50051"
directories:
  data: /home/chad/.arduino15
  downloads: /home/chad/.arduino15/staging
  user: /home/chad/Arduino
library:
  enable_unsafe_install: false
logging:
  file: ""
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
output:
  no_color: false
sketch:
  always_export_binaries: false
updater:
  enable_notification: true
```

>     * Do you know if the `-cli` and `-clangd` options are needed?  If yes, we could make sure to install `arduino-cli` and `clangd` as well.

[`arduino-cli` is indeed required](https://github.com/arduino/arduino-language-server#usage) and we can install it and pass its path with `-cli`. [I'm unsure whether `clangd` is actually required](https://github.com/arduino/arduino-language-server/search?q=clangd), but it couldn't hurt to handle it likewise.
